#!/usr/bin/env bash
# Display information about subdomains.

display_info() {
    local domain="$1"
    local subdomain="$2"

    local result
    result=$(dig "$subdomain.$domain" +short | awk 'NR==1{print $1}')

    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a $result record and points to $domain"
    else
        echo "No information found for subdomain $subdomain"
    fi
}

if [ "$#" -eq 1 ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        display_info "$1" "$subdomain"
    done
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
