#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

echo "server {
   listen 80;
   listen [::]:80;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://upschool.com/register;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
   location / {
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

nginx -t

service nginx restart
