#!/usr/bin/env bash
# Fix NGINX listening on port 80

# Go to sites-enabled folder for NGINX
cd /etc/nginx/sites-enabled/ || exit

# Check if the default file exists before removing it
if [ -e default ]; then
	rm default
fi

# Create a symbolic link to the default file in sites-available
ln -s /etc/nginx/sites-available/default default

# Make changes in the NGINX configuration and test
nginx -t

# Restart NGINX only if it's not already running
if ! service nginx status > /dev/null; then
	service nginx restart
fi
