#!/bin/bash
# File to read
file="/etc/passwd"
if [ ! -e "$file" ]; then
	echo "Error: $file does not exist."
	exit 1
fi

while IFS=: read -r username password uid gid info home shell
do
	echo "The user $username is part of the $gid gang, lives in $home, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "$file"
