#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
for file in *
do
	if [[ "$file" == .* ]]; then
		continue
	fi

	if [[ "$file" == *-* ]]; then
		echo "${file#*-}"
	else
		echo "$file"
	fi
done
