#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs
interfaces=$(ls /sys/class/net)
for interface in $interfaces
do
	ip=$(ip -4 -o addr show "$interface" | awk '{print $4}')
	if [ -n "$ip" ]
	then
		cut_ip=$( echo "$ip" | cut -d'/' -f1)
		echo "$cut_ip"
	fi
done
