#!/usr/bin/env bash
# a Bash script that  run the whoami command under the user passed as an argument

# Check if username argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

username="$1"

# Run whoami command as the specified user
sudo -u "$username" whoami
